final Map<String, String> en = {
  "1bL_0": "0",
  "1bL_00_06": "00-06",
  "1b1_012345678955": "012345678955",
  "1bL_01_26": "01:26",
  "1bL_100": "100%",
  "1bl_102_kwh": "102 KWh",
  "Ibl_10_am": "10 AM",
  "IbL_12": "+12%",
  "1bl_12_am": "12 AM",
  "1bl_16_22_april": "16-22 April",
  "1bl_175_bpm": "175 BPM",
  "IbL_1_pm": "1 PM",
  "LbL_20": "20",
  "1bl_2000_kwh": "2000 KWh",
  "1bl_23_29_april": "23-29 April",
  "Ibl_2_5_hours": "2.5 hours",
  "Lbl_2_am": "2 AM",
  "Ibl_2_devices": "2 devices",
  "Ibl_309": "309",
  "ZbL_309_kwh": "309 KWh",
  "1bL_350_kwh": "350 kWh.\"",
  "1bl_350_kwh2": "350 KWh",
  "lbl_398kwh": "398KWh",
  "1bL_40": "40",
  "1bL_402": "40%",
  "1bL_45": "45%",
  "Ibl_4_am": "4 AM",
  "1bL_50": "50%",
  "Ibl_523_kwh": "523 KWh",
  "1bL_55": "55%",
  "1bl_6": "(6)",
  "1bl_60": "60%",
  "1bL_62": "6",
  "1bl_6_am": "6 AM",
  "Ibl_6_am_4_am": "6 AM - 4 AM",
  "1bL_70": "70%",
  "IbL_725_kwh": "725 KWh",
  "1bL_75kwh": "75KWh",
  "Ibl_7_devices": "7 devices",
  "1bl_80": "80%",
  "1bl_80k": "\$80K",
  "1bl_888": "*888*******",
  "Ibl_888_fresh": "888 fresh",
  "Ibl_888_1g": "888 LG",
  "Ibl_888_samsung": "888 samsung",
  "Ibl_888_sony": "888 sony",
  "Ibl_888sony2": "888sony",
  "IbL_89": "89%",
  "Ibl_8_am": "8 AM",
  "Ibl_ac": "AC",
  "Ibl_add_device": "Add Device",
  "Ibl_add_more_device": "Add More Device",
  "Ibl_altersol": "AlterSol",
  "Ibl_back_to_home": "Back to Home",
  "Ibl_battery": "Battery",
  "Ibl_call_us": "Call Us",
  "Ibl_change_password": "Change Password",
  "Ibl_continue": "Continue",
  "Ibl_day": "Day",
  "Ibl_delete_account": "Delete Account",
  "Ibl_devices": "Devices",
  "Ibl_devices_6": "Devices (6)",
  "Ib_email": "Email",
  "Ibl_exported": "Exported",
  "Ibl_f": "F",
  "Ibl_femal": "Femal",
  "Ibl_forgot_password": "Forgot Password",
  "Ibl_fridge": "Fridge",
  "Ibl_from_last_month": " from last month",
  "Ibl_gender": "Gender",
  "Ibl_handel_the": "Handel the\n",
  "Ib_help": "Help",
  "Ibl_hightlight": "Hightlight ",
  "Ibl_home": "Home",
  "Ibl_jan": "Jan",
  "Ib_jan_des": "Jan - Des",
  "Ibl_kwh": " KWh",
  "Ibl_lamp": "Lamp",
  "Ibl_laptop": "Laptop",
  "Ibl_log_in": "Log In",
  "Ibl_log_in2": " Log In",
  "Ibl_log_out": "Log out ",
  "Ibl_m": "M",
  "Ibl_mansoura": "mansoura",
  "Ibl_message": "Message",
  "Ibl_message_us": "Message Us",
  "Ibl_month": "Month",
  "Ibl_name": "Name",
  "Ibl_new_password": "New Password",
  "Ibl_next": "Next",
  "Ibl_no_message": "No message",
  "Ibl_notification": "Notification",
  "Ibl_notifications": "Notifications",
  "Ibl_or": "or",
  "Ibl_panels": "Panels",
  "Ibl_password": "Password",
  "Ibl_pc": "PC",
  "Ibl_personal_info": "Personal info",
  "Ibl_phone": "phone",
  "Ibl_privacy_policy": "Privacy policy",
  "Ibl_privacy_policy2": "Privacy Policy",
  "Ibl_produce": "Produce",
  "Ibl_projector": "Projector",
  "Ibl_read_all": "Read All",
  "Ibl_remember_me": "Remember me",
  "Ibl_resend_code": "Resend code",
  "Ibl_reset_password": "Reset Password",
  "Ibl_reset_password2": "Reset password",
  "Ibl_s": "S",
  "Ibl_save_more_with": "Save More with ",
  "Ib_search_brand": "Search Brand",
  "Ibl_select_tv": "select TV",
  "Ibl_settings": "Settings",
  "Ibl_sh_123456": "sh #123456",
  "Ibl_shereen_amgad": "Shereen Amgad",
  "Ibl_shereen_amgad2": "shereen amgad",
  "Ibl_shereenamgad2": "shereenamgad",
  "Ibl_siaray": "SiaRay",
  "Ibl_sign_up": "Sign Up",
  "Ubl_skip": "Skip",
  "Ibl_smart_energy": "Smart Energy",
  "Ibl_smart_lamp": "smart lamp",
  "Ibl_smart_tv": "smart TV",
  "Ibl_smart_tv2": "Smart TV",
  "Ibl_solar_panel": "Solar panel",
  "Ibl_solar_panel2": "Solar panel ",
  "Ibl_sony": "Sony",
  "Ibl_statisric": "Statisric",
  "Ibl_statistics": "Statistics",
  "Ibl_stored_energy": "Stored Energy",
  "Ibl_t": "T",
  "Ibl_talk_to_ai": "Talk to Ai",
  "Ibl_this_month": "This Month",
  "Ibl_this_month2": "this Month",
  "Ibl_this_week": "This Week",
  "Ibl_time_usage": "Time usage",
  "Ibl_today": "Today",
  "Ibl_update_profile": "Update profile",
  "Ibl_used_in_battery": "Used in battery",
  "Ibl_user_name": "User name",
  "Ibl_verify": "verify",
  "Ibl_w": "W",
  "?bl_week": "Week",
  "Ibl_weekly": "Weekly",
  "Ibl_welcome": "Welcome ",
  "Ibl_welcome_back": "Welcome back",
  "Ibl_welcome_back2": "Welcome back,",
  "Ibl_wifi": "WiFi",
  "Ib_with": " with\n ",
  "msg_12_from_last_month": "+12% from last month",
  "msg_a90j_bravia_xp": "A90J | BRAVIA XP",
  "msg_all_notification": "All Notification",
  "msg_ask_me_anything": "Ask me anything...",
  "msg_at_least_8_characters": "At least & characters",
  "msg_cancelation_policy": "Cancelation Policy",
  "msg_confirm_password": "Confirm Password",
  "msg_confirm_password2": "Confirm password ",
  "msg_create_a_new_password": "Create a new password for \nyour account",
  "msg_current_password": "Current Password",
  "msg_customer_support": "Customer Support",
  "msg_do_you_have_an_account": "Do you have an account ?",
  "msg_do_you_have_an_account2": "Do you have an account ? Log In",
  "msg_don_t_have_an_account": "Don't have an account ? ",
  "msg_don_t_have_an_account2": "Don't have an account ? Sign Up",
  "msg_electricity_consumed": "Electricity consumed",
  "msg_energy_you_produce": "energy you Inproduce",
  "msg_enjoy_independent":
      "Enjoy independent electricity and monitor\nyour solar panel performance in rea",
  "msg_enter_your_email": "Enter your email account to\nreset your password",
  "msg_faster_easy_beautiful": "faster\neasy\nbeautiful",
  "msg_forgot_password": "Forgot password?",
  "msg_generated_electricity": "Generated electricity",
  "msg_handel_the_energy": "Handel the\nenergy you Inproduce",
  "msg_how_may_i_help_you": "How may i help you today?",
  "msg_let_s_start_this": "Let's start this journey",
  "msg_lorem_ipsum_dolor":
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  "msg_lorem_ipsum_dolor2":
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  "msg_lorem_ipsum_dolor3":
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  "msg_lorem_ipsum_dolor2":
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  "msg_lorem_ipsum_dolor3":
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  "msg_lower_your_electricity":
      "\"Lower your electricity bills while making a positive impact.®Track savings ar",
  "msg_messages_from_the": "Messages from the team will be show \nhere",
  "msg_notification_settings": "Notification Settings",
  "msg_on_average_your": "On average, your energy production last week",
  "msg_optimize_again_to": "Optimize again to get your best score",
  "msg_otp_verification": "OTP Verification",
  "msg_password_manager": "Password Manager",
  "msg_peak_solar_energy": "\"Peak solar energy production was at ",
  "msg_peak_solar_energy2":
      "\"Peak solar energy production was at 1 PM with\n 350 kWh.\"",
  "msg_performance_monitoring": "Performance monitoring",
  "msg_please_check_your":
      "Please check your email jack123@gmail.com\nto see verification code",
  "msg_save_more_with_smart": "Save More with Smart Energy",
  "msg_saving_in_battery": "saving in battery",
  "msg_send _us_a_message": "send us a message",
  "msg_shereen_amgad29_gmail_com": "shereen.amgad29@gmail.com",
  "msg_solar_panel_points": "Solar panel points",
  "msg_solar_panel_points2": "Solar panel points (6)",
  "msg_solar_panel_statistics": "Solar panel statistics",
  "msg_successfully_verification": "Successfully Verification",
  "msg_terms_condition": "Terms & Condition",
  "msg_total_energy_production": "Total Energy Production",
  "msg_total_generation": "Total generation",
  "msg_tv_brand_model": "TV Brand & Model",
  "msg_we_home_internet": "we Home internet",
  "msg_your _device_added": "Your Device Added\n Successfully!",
  "err_msg_please_enter_valid_email": "Please enter valid email",
  "err_msg_please_enter_valid_password": "Please enter valid password",
  "err_msg_please_enter_valid_phone_number": "Please enter valid phone number",
  "err_msg_please_enter_valid_text": "Please enter valid text",
  "err_msg_field_cannot_be_empty": "Field cannot be empty",
  "msg_network_err": "Network Error",
  "msg_something_went_wrong": "Something Went Wrong!",
};
